### ISSUE TITLE
Multiple Records at once

### ISSUE THREAD

**Issue by Zeeanq** [FarrowStrange/hetzner-api-dyndns#19]
I am setting up a local webserver for me and ofcourse some friends.
i am testing this script and its very helpful.

But my question: Is it possible to issue changes on Multiple Records like -Z example.com -n dyn -n @ or -Z example.com -n dyn,@
or something like that

**Comment by FarrowStrange** [comment]
Hey @Zeeanq,

Currently it is not possible to pass multiple records to the script at once. 

I see two possibilities here:

You could create a record with the help of the script and update it continuously. You can then reference the other records in the DNS console with a CNAME record.

**For example:**
```
dyn     IN     A      203.0.113.20
www     IN     CNAME  dyn
mail    IN     CNAME  dyn
...
```

Alternatively, you can call the script multiple times to set several different records. However, I haven't tested what happens if you call the script multiple times at the same time. You may have to define different runtimes for the crontab entries.

**Example Crontab entry:**

```
HETZNER_AUTH_API_TOKEN='<your-hetzner-dns-api-token>'

*/5 * * * * /usr/bin/dyndns.sh -Z example.com -n dyn
*/5 * * * * /usr/bin/dyndns.sh -Z example.com -n www
*/5 * * * * /usr/bin/dyndns.sh -Z example.com -n mail

```


I hope I was able to help you with your question. If you have any questions or problems, please feel free to contact me here.

**Comment by Zeeanq** [comment]
thank you. 
i will give them both a try. 

which one is the most reliable?

**Comment by FarrowStrange** [comment]
Primarily I would use CNAME Records.

I would be happy if you could give me feedback afterwards and share your experiences.

**Comment by Zeeanq** [comment]
After a while of testing and gathering experience with the api i can say the method with CNAME was indeed the best option.

Thank you for your advise.
