### ISSUE TITLE
Script creates new A record instead of updating current one

### ISSUE THREAD

**Issue by Breit** [FarrowStrange/hetzner-api-dyndns#22]
First of all: Very nice script, thanks a lot!

I set the script up here at home with the HETZNER_AUTH_API_TOKEN put in the script as well as HETZNER_ZONE_NAME and HETZNER_RECORD_NAME and let cron just execute the script without any additional parameters.
This worked fine at first, no errors, just updating the record as it's supposed to. The cronjob run every minute with a default TTL of 60.

Now one day later I figured that I had 2 pairs of identical records (4 total) in my DNS zone instead of only one?!
Maybe that was caused by rapidly changing IP addresses, because I fiddled around with my networking gear yesterday and had a few reconnects with different IP addresses because of that?

Anyway, if there is more than one identical record in the zone to be updated, then the script failes to do so. Maybe because it does not know which one to update?
Another question is, how those multiple entries got there in the first place. Maybe due to rapid IP address change, the IP address query can report more than one IPv4 address?

**Comment by cloonix** [comment]
I had the same problem. Deleted all records and now it seems to work fine again. Maybe a hick-up on the API's end.

**Comment by Breit** [comment]
I re-implemented my cronjob and now specify the exact record ID. This way it *should* not double the entries anymore. We'll see.

**Comment by FarrowStrange** [comment]
Hey @Breit,

Thanks for the praise. 😄 

In fact this is a behavior I haven't seen before. Actually, this should only happen if the API response does not return a "**record_id**" for the specified „**record_name**“. In this case the script would create a new record instead of updating an existing one.

Currently I can only guess how this happens, but I will do some tests to check the accessibility of the Hetzner DNS API and the corresponding responses. 🤔 

In any case, a very good idea to define the exact „record _id“ - this way no duplicates should be created. Did you have any problems after that?

Also many thanks to @cloonix , who has contributed his knowledge here. It is always nice to see when others share their experiences. 🚀

**Comment by Breit** [comment]
No, since I explicitly replaced record_name with the record_id, everything is smooth.
Thanks again for this great script.

**Comment by FarrowStrange** [comment]
I am still testing why two records are created from time to time. In my tests, in one of about 30 runs, two records were created during the initial run of the script.

**Comment by denisplt** [comment]
I experienced the same issue. I don't know when exactly it occured, since I didn't check my DNS Entries for quite a while.
In my case the IP didn't change in the time where the duplicated entries appeared, so they all had the same IP.

I have 2 entries @.domain.de and dyn.domain.de, which I keep updated with your script.

`*/5 * * * * /usr/bin/dyndns.sh -n dyn -t 360`

`*/5 * * * * /usr/bin/dyndns.sh -n @ -t 360`

I noticed, that my version of your script,  is pretty close to the master branch, but only checking if jq is installed and not all 3 dependencies.

I will add log the output of your script. Maybe I can help you if the issue appears again.

**Comment by denisplt** [comment]
I restarted my router yesterday and suddenly all of my services were down...
I thought this could be due to a double DNS entry with different IPs -> Checked my DNS Entries -> no double entries, but my IP Address didn't change...

Turns out, that i forgot to edit the environment variables inside of the Script after upgrading to a newer version... :smile: 

I am not sure, if it would make sense to save the environment variables to a separate file to prevent this issue.
Anyways -> the issue didn't occur within the last 16 days, because I f'ed up my script :laughing: 

I will keep you updated, if the original issue occurs again.

**Comment by FarrowStrange** [comment]
@gollum3003 Sorry for the late feedback. Unfortunately i had a lot to do, which made the private projects fall into the background a bit. 

It has been suggested several times to create an .env file. There is also one or the other fork, which has rebuilt this for itself. The majority of users use the script in combination with the crontab and set their environment variables here. 
But I will make a note of it and maybe create an additional possibility for an .env file.

**Comment by FarrowStrange** [comment]
The good news is that I have merged the PR https://github.com/FarrowStrange/hetzner-api-dyndns/pull/25 and the script is now available in version `1.2`. Many thanks to @Breit for the review 🤙🏽 

The changes take into account the HTTP status code of the API call to prevent duplicate records from being created. 
So this issue should finally be closed 😄
